### ISSUE TITLE
Use more pythonic way for pinging bluetooth device

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#11]
https://github.com/LethalEthan/Bluetooth-Unlock/blob/8041e91e53c5367e95862ff700e1e47e860b7cfa/Bluetooth-Unlock.py#L146

you may want to check and test a "non-lame" approach for bluetooth ping mentioned in https://github.com/jeffbryner/bluetoothscreenlock/blob/master/bluetoothscreenlock.py

**Comment by LethalEthan** [comment]
I have tried that script with my phone it hasn't work, but thanks for suggesting a better way to do it. Since it was 2012 something may have changed and has broken it. but for now, the current method still works and is reliable.
