### ISSUE TITLE
logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [LethalEthan/Bluetooth-Unlock#12]
want to make a logo for this projects if you have any requirements then let me know.its free for open source projects.
Thank you

**Comment by LethalEthan** [comment]
Yes that would be great

**Comment by LethalEthan** [comment]
Something with the Bluetooth logo in it

**Comment by LethalEthan** [comment]
Also sorry if I don't reply for a long time my internet is down and I'm using mobile data. Also I spilt coke all over my laptop :disappointed: so I'm currently fixing that aswell

**Comment by masudr4n4** [comment]
its ok i am waiting  for you.no problem.

**Comment by LethalEthan** [comment]
Right, my internet is back up and running now, just waiting for a technician to properly fix it

**Comment by LethalEthan** [comment]
Laptop is ok btw

**Comment by LethalEthan** [comment]
My internet is still a bit broken

**Comment by maaudrana** [comment]
its okey 
bro relax .

**Comment by LethalEthan** [comment]
Just want to keep you informed on what's going on

**Comment by LethalEthan** [comment]
I think having a lock next to the Bluetooth symbol would look quite nice

**Comment by LethalEthan** [comment]
Hey, are you still working on the logo? If so how is it going?
