### ISSUE TITLE
Saving options to config file

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#2]
please add a possibility to save chosen options into config file. it's not really user friendly to have user enter the same data over and over.

**Comment by LethalEthan** [comment]
Yes, I'm trying to get python3 to create a .ini or .json file for a config but haven't found a good way to do it yet, but I will try my best to implement it.

**Comment by jose1711** [comment]
great. please take a look at https://docs.python.org/2/library/configparser.html which may be a ready-to-use solution

**Comment by LethalEthan** [comment]
Thanks for the suggestion I will implement that right away

**Comment by LethalEthan** [comment]
There seems to be a problem with configparser no matter what I do it always throws an error. I am trying to use json because of it.

**Comment by LethalEthan** [comment]
Nevermind I have fixed the problem and will be implementing soon
