### ISSUE TITLE
Install.sh is only useful for Debian-based distros

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#4]
```Install.sh``` only relies on presence of apt package manager. No support for major RPM-based distros (Fedora, Suse, possibly a few others) or pacman (Arch Linux and derivates).

**Comment by LethalEthan** [comment]
Yes I know, I am currently working on that, I am trying to get bash to auto-detect the package manager. Thanks for pointing that out :smile:

**Comment by LethalEthan** [comment]
Trying to auto-detect the package manager in bash hasn't worked for me in any way, so I'm kind of stuck unless I do a menu system which personally I don't like, I'd rather have it auto detect, but I haven't found a good way yet. Any suggestions would be great.

**Comment by jose1711** [comment]
you could parse ```lsb_release -a``` output to get linux distro name and map it to appropriate package manager and package names. or forget about downloading dependencies automatically and make a note in the README (that is: make users themselves responsible).

**Comment by LethalEthan** [comment]
I could use lsb_release -i to a variable called distro and do what you said and map it to the appropriate package manager
