### ISSUE TITLE
Do not offer a choice to compile python3 manually

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#6]
Why would anyone want to use a self-compiled python3 binaries instead of a (often digitally signed) package from an official repository? By doing ```sudo make install``` you're only calling for problems (future conflicts with package manager). Ok, asking if a user wants to install python3 is a good idea but why not to simply run ```apt install python3```?

**Comment by LethalEthan** [comment]
I was trying to get all distro's working but ran into some issues and this was the easiest way to do this, currently working on a better feature
