### ISSUE TITLE
User should not be presented with options containing missing requisites

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#9]
I don't think it is a good idea to present all options no matter if - say - gnome-screensaver-command is available or not. Script should first detect what commands are available and then let the user choose. Also there's a lot of duplicated code in "calling screensaver" section towards the end of the script - it would be nice to clean it up a bit.

**Comment by LethalEthan** [comment]
Yes that is a good idea but computers with multiple desktops such as having gnome and KDE it won't work

**Comment by jose1711** [comment]
Can you please elaborate? What have multiple desktops to do with unavailability of certain screensavers on - say - a standard Debian system?

**Comment by LethalEthan** [comment]
Each screensaver needs a different command and the user specifies it at the first run but autodetecting would get confused on a pc which has multiple desktop environments such as mine.

**Comment by jose1711** [comment]
i am not suggesting preselecting any autodetected screensaver. user however should be at least notified if a given command is unavailable. something like this:
```
LOGINCTL
KDE
GNOME (gnome-screensaver-command not installed)
XSCREENSAVER (xscreensaver not installed)
MATE
CINNAMON
```

**Comment by LethalEthan** [comment]
Good idea but I'm not sure how I'm going to do this  :confused:

**Comment by jose1711** [comment]
it is quick safe to assume that if - say - ```gnome-screensaver``` is installed you'll be able to just call it relying on standard PATH. so you can do something like this:
```
from distutils.spawn import find_executable
env_screensaver = {'GNOME': 'gnome-screensaver', 'MATE': 'mate-screensaver-command', 'XSCREENSAVER': 'xscreensaver'}
for env in env_screensaver:
    if find_executable(env_screensaver[env]):
      ...
    else:
      ...
```

**Comment by LethalEthan** [comment]
It seems to work quite well implementing it asap
